### PR TITLE
Update to jupyterlab-2.0

### PR DESCRIPTION
**Pull request by ghost**
I upgrade your plugin to jupyterlab 2.0

Thanks for your work

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks a lot @ogiorgis, really appreciated!

**Comment by ghost** [comment]
with pleasure.
Could you please also publish the new version on npm ?

**Comment by jtpio** [comment]
Just published 0.4.0.

**Comment by ghost** [comment]
Great ! Thanks a lot.

**Comment by jtpio** [comment]
By the way @ogiorgis, it looks like your are not getting credits for your contribution.

You would have to add the email address used for the commit (`git show add68e` to get it) to your [GitHub account](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account).

**Comment by ghost** [comment]
ok thanks

**Pull request merged**
